# Generated by Django 5.2.8 on 2025-11-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(max_length=150)),
                ('user_question', models.CharField()),
                ('model_answer', models.CharField()),
            ],
        ),
    ]
